apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mydeploy-02
  namespace: default
  labels:
    app:  canary-nginx-deploy-test2
spec:
  replicas: 4
  selector:
    matchLabels:
      app: canary-nginx
      v: v2
  template:
    metadata:
      labels:
        app:  canary-nginx
        v: v2
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name: nginix-02
        image: nginx:1.21.6-alpine-perl
        imagePullPolicy: IfNotPresent
