apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: lyf-2
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lyf-admin
subjects:
- kind: ServiceAccount
  name: lyf-2
  namespace: default
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io  