apiVersion: apps/v1
kind: Deployment
metadata:
  name:  remove-existing-pod
  namespace: default
  labels:
    app:  remove-existing-pod
spec:
  selector:
    matchLabels:
      app: startup-probe
  replicas: 1
  template:
    metadata:
      labels:
        app:  startup-probe
    spec:
      containers:
      - name:  alpine
        image:  alpine
        imagePullPolicy: IfNotPresent
