apiVersion: v1
kind: Pod
metadata:
  name: "my-mysql"
  namespace: hello
  labels:
    app: "my-mysql"
spec:
  containers:
  - name: my-mysql
    image: mysql:5.7.34
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: 123456
    - name: MYSQL_DATABASE
      value: itdachang
