apiVersion: apps/v1
kind: Deployment
metadata:
  name:  deploy-rollupdate
  namespace: default
  labels:
    app:  test-rollupate
spec:
  replicas: 5
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rollupdate
  template:
    metadata:
      labels:
        app:  rollupdate
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  nginix-01
        image:  nginx
        imagePullPolicy: IfNotPresent
