apiVersion: v1
kind: Pod
metadata:
  name: "multi-container"
  namespace: default
  labels:
    app: "multi-container"
spec:
  volumes:
  - name: nginxvol
    emptyDir: {}
  containers:
  - name: nginx-container
    image: "nginx"
    volumeMounts:
    - name: nginxvol
      mountPath: /usr/shar/nginx/html
  - name: content-container
    image: "alpine"
    command: ["/bin/bash", "-c", "while true; do sleep 1; date > /app/index.html; done;"]
    volumeMounts:
    - name: nginxvol
      mountPath: /app
