apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: my-network-policy-01
  namespace: default
spec:
  podSelector: 
    matchlabels:
      app: pppp
  policyTypes:
  - "Ingress":
  - "Egress": 
  ingress: 
    from: 
    - podSelector: 
  egress: 