apiVersion: v1
kind: Pod
metadata:
  name: "pod-nfs-01"
  namespace: default
  labels:
    app: "pod-nfs-01"
spec:
  containers:
  - name: pod-nfs-01
    image: "nginx"
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort:  80
      name:  http
    volumeMounts:
    - name: localtime
      mountPath: /etc/localtime
    - name: html
      mountPath: /usr/share/nginx/html
  volumes:
    - name: localtime
      hostPath:
        path: /usr/share/zoneinfo/Asia/Shanghai
    - name: html
      nfs:
        server: 192.168.1.200
        path: /nfs/data/nginx
