apiVersion: v1
kind: Pod
metadata:
  name: "pod-secret-test"
  namespace: default
  labels:
    app: "pod-secret-test"
spec:
  containers:
  - name: pod-secret-test
    image: "busybox"
    command: ["/bin/sh", "-c", "sleep 3600"]
    env:
    - name: MY_USR
      valueFrom:
        secretKeyRef:
          name: dev-db-secret
          key: username
    - name: POD_NAME
      valueFrom:
        fieldRef: 
          fieldPath: metadata.name
    - name: POD_LIMIT_MEM
      valueFrom:
        resourceFieldRef:
          containerName: pod-secret-test
          resource: limits.cpu
    imagePullPolicy: IfNotPresent

