apiVersion: v1
kind: Pod
metadata:
  name: "taints-test"
  namespace: default
  labels:
    app: "taints-test"
spec:
  containers:
  - name: taints-test
    image: "busybox"
    command: ["/bin/sh", "-c", "sleep 30"]
    imagePullPolicy: IfNotPresent
  tolerations:
  - key: haha
    value: hehe
    effect: NoSchedule
  restartPolicy: Always