apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: lyf
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # namespace: default
  name: ns-reader
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-ns-global
subjects:
- kind: ServiceAccount
  name: lyf
  namespace: default
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: ns-reader
  apiGroup: rbac.authorization.k8s.io  