apiVersion: v1
kind: Service
metadata:
  name: canary-test
  namespace: default
spec:
  selector:
    app: canary-nginx
  type: NodePort
  ports:
  - name: canary-test
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31666