apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-test-01
  namespace: default
  labels:
    app: nfs-pv-test-01
spec:
  storageClassName: my-nfs-pv-10m-storage
  capacity:
    storage: 10m
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 192.168.1.200
    path: /nfs/data/haha
    