kind: Pod
apiVersion: v1
metadata:
  name: my-command-test
  namespace: hello
spec:
  containers:
  - image: nginx
    name: command-test
    command:
    - /bin/sh
    - -c
    - "echo $(msg); sleep 3600;"
    env:
    - name: msg
      value: "hello msg"
